[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "msps"
version = "1.0.2"
description = "Maven Settings Profile Switcher"
authors = [{ name = "István Földházi", email = "istvan.foldhazi@gmail.com" }]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["rich>=14.0.0", "typer>=0.19.0"]

[project.optional-dependencies]
test = [
  "pytest>=8.0.0",
  "coverage>=7.4.3",
  "tox>=4.13.0",
  "pytest-cov>=6.0.0",
  "mypy>=1.8.0",
  "pylint>=3.0.3",
]
typing = ["mypy>=1.8.0"]
lint = ["pylint>=3.0.3"]
dev = [
  "black>=25.0.0",
  "pytest-sugar>=1.0.0",
  "pytest-cov>=6.0.0",
  "isort>=5.13.2",
  "deptry>=0.22.0",
  "twine>=6.0.0",
]

[project.scripts]
msps = "msps.__main__:main"

[tool.setuptools.packages.find]
where = ["src"]
include = ["msps*"]

[tool.mypy]
packages = "src"
disable_error_code = "import-untyped"
namespace_packages = true
explicit_package_bases = true
show_error_codes = true
strict = true

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.isort]
profile = "black"

[tool.deptry]
optional_dependencies_dev_groups = ["test", "dev", "typing", "lint"]

[tool.deptry.per_rule_ignores]
DEP003 = ["msps"]

[tool.pylint.messages_control]
disable = [
  "C0114",
  "C0115",
  "C0116",
  "R0903",
  "R1735",
  "W0622",
]
