name: Publish to TestPyPI

on:
  workflow_dispatch:

permissions: read-all

jobs:
  release-test:
    name: Publish to TestPyPI
    runs-on: ubuntu-latest

    environment:
      name: release-test
      url: https://test.pypi.org/p/msps

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
          cache: poetry

      - name: Install packages
        run: poetry install

      - name: Bump version
        run: poetry version "$(poetry version --short)${GITHUB_RUN_NUMBER}"

      - name: Build
        run: poetry build

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
