name: Test

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.10", "3.11", "3.12"]

    runs-on: ubuntu-latest

    steps:
      - name: Update python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
          architecture: x64

      - name: Install Poetry
        run: curl -sSL curl -sSL https://install.python-poetry.org | python3 -

      - name: Set env
        run: echo "PATH=${PATH}:$HOME/.poetry/bin" >> $GITHUB_ENV

      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install packages via Poetry
        run: poetry install

      - name: Check type annotations
        run: poetry run mypy

      - name: Check code style
        run: poetry run pylint msps
