name: Test

on:
  push:
    branches-ignore:
      - main

permissions: read-all

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.13", "3.14"]

    runs-on: ubuntu-latest

    steps:
      - name: Update python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python_version }}
          architecture: x64

      - name: Install UV
        uses: astral-sh/setup-uv@v8.1.0

      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Install packages via UV
        run: uv sync --extra test

      - name: Run tests with coverage
        run: uv run coverage run --branch --module pytest

      - name: Check type annotations
        run: uv run mypy

      - name: Check code style
        run: uv run pylint src/msps
<<<<<<< HEAD
=======

  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Update python
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"
          architecture: x64

      - name: Install UV
        uses: astral-sh/setup-uv@v8.1.0

      - name: Checkout branch
        uses: actions/checkout@v6
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Install packages via UV
        run: uv sync --extra test

      - name: Run tox
        run: uv run tox -e py

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          JAVA_HOME: /opt/java/openjdk
          SONAR_SCANNER_HOME: /opt/sonar-scanner
>>>>>>> f395c1860cd8030738f01ec5147bfcc1221d5226
