name: Test

on:
  push:
    branches-ignore:
      - main

permissions: read-all

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.13", "3.14"]

    runs-on: ubuntu-latest

    steps:
      - name: Update python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python_version }}
          architecture: x64

      - name: Install UV
        uses: astral-sh/setup-uv@v7

      - name: Checkout branch
        uses: actions/checkout@v5

      - name: Install packages via UV
        run: uv sync --extra test

      - name: Run tests with coverage
        run: uv run coverage run --branch --module pytest

      - name: Check type annotations
        run: uv run mypy

      - name: Check code style
        run: uv run pylint src/msps
